MODULE ODE_SOLVER
    TYPE RK_DERIVS_TYPDEF
        LOGICAL::ISOUTOFRANGE=.FALSE.
        REAL(8)::HF_SUC=0.0D0,HF_FAIL=0.0D0
        INTEGER::IEL=0,LASTIEL=0 !LASTIEL=在积分路径离开积分区域前时所在的单元
        
    ENDTYPE
    TYPE(RK_DERIVS_TYPDEF)::RKINFO
    
END MODULE    