MODULE VTK_CELLTYPE
	IMPLICIT  NONE
  ! Linear cells
  INTEGER, PARAMETER :: VTK_EMPTY_CELL = 0
  INTEGER, PARAMETER :: VTK_VERTEX = 1
  INTEGER, PARAMETER :: VTK_POLY_VERTEX = 2
  INTEGER, PARAMETER :: VTK_LINE = 3
  INTEGER, PARAMETER :: VTK_POLY_LINE = 4
  INTEGER, PARAMETER :: VTK_TRIANGLE = 5
  INTEGER, PARAMETER :: VTK_TRIANGLE_STRIP = 6
  INTEGER, PARAMETER :: VTK_POLYGON = 7
  INTEGER, PARAMETER :: VTK_PIXEL = 8
  INTEGER, PARAMETER :: VTK_QUAD = 9
  INTEGER, PARAMETER :: VTK_TETRA = 10
  INTEGER, PARAMETER :: VTK_VOXEL = 11
  INTEGER, PARAMETER :: VTK_HEXAHEDRON = 12
  INTEGER, PARAMETER :: VTK_WEDGE = 13
  INTEGER, PARAMETER :: VTK_PYRAMID = 14
  INTEGER, PARAMETER :: VTK_PENTAGONAL_PRISM = 15
  INTEGER, PARAMETER :: VTK_HEXAGONAL_PRISM = 16

  ! Quadratic isoparametric cells
  INTEGER, PARAMETER :: VTK_QUADRATIC_EDGE = 21
  INTEGER, PARAMETER :: VTK_QUADRATIC_TRIANGLE = 22
  INTEGER, PARAMETER :: VTK_QUADRATIC_QUAD = 23
  INTEGER, PARAMETER :: VTK_QUADRATIC_POLYGON = 36
  INTEGER, PARAMETER :: VTK_QUADRATIC_TETRA = 24
  INTEGER, PARAMETER :: VTK_QUADRATIC_HEXAHEDRON = 25
  INTEGER, PARAMETER :: VTK_QUADRATIC_WEDGE = 26
  INTEGER, PARAMETER :: VTK_QUADRATIC_PYRAMID = 27
  INTEGER, PARAMETER :: VTK_BIQUADRATIC_QUAD = 28
  INTEGER, PARAMETER :: VTK_TRIQUADRATIC_HEXAHEDRON = 29
  INTEGER, PARAMETER :: VTK_QUADRATIC_LINEAR_QUAD = 30
  INTEGER, PARAMETER :: VTK_QUADRATIC_LINEAR_WEDGE = 31
  INTEGER, PARAMETER :: VTK_BIQUADRATIC_QUADRATIC_WEDGE = 32
  INTEGER, PARAMETER :: VTK_BIQUADRATIC_QUADRATIC_HEXAHEDRON = 33
  INTEGER, PARAMETER :: VTK_BIQUADRATIC_TRIANGLE = 34

  ! Cubic isoparametric cell
  INTEGER, PARAMETER :: VTK_CUBIC_LINE = 35

  ! Special class of cells formed by convex group of points
  INTEGER, PARAMETER :: VTK_CONVEX_POINT_SET = 41

  ! Polyhedron cell (consisting of polygonal faces)
  INTEGER, PARAMETER :: VTK_POLYHEDRON = 42

  ! Higher order cells in parametric form
  INTEGER, PARAMETER :: VTK_PARAMETRIC_CURVE = 51
  INTEGER, PARAMETER :: VTK_PARAMETRIC_SURFACE = 52
  INTEGER, PARAMETER :: VTK_PARAMETRIC_TRI_SURFACE = 53
  INTEGER, PARAMETER :: VTK_PARAMETRIC_QUAD_SURFACE = 54
  INTEGER, PARAMETER :: VTK_PARAMETRIC_TETRA_REGION = 55
  INTEGER, PARAMETER :: VTK_PARAMETRIC_HEX_REGION = 56

  ! Higher order cells
  INTEGER, PARAMETER :: VTK_HIGHER_ORDER_EDGE = 60
  INTEGER, PARAMETER :: VTK_HIGHER_ORDER_TRIANGLE = 61
  INTEGER, PARAMETER :: VTK_HIGHER_ORDER_QUAD = 62
  INTEGER, PARAMETER :: VTK_HIGHER_ORDER_POLYGON = 63
  INTEGER, PARAMETER :: VTK_HIGHER_ORDER_TETRAHEDRON = 64
  INTEGER, PARAMETER :: VTK_HIGHER_ORDER_WEDGE = 65
  INTEGER, PARAMETER :: VTK_HIGHER_ORDER_PYRAMID = 66
  INTEGER, PARAMETER :: VTK_HIGHER_ORDER_HEXAHEDRON = 67

  ! Arbitrary order Lagrange elements (formulated separated from generic higher order cells)
  INTEGER, PARAMETER :: VTK_LAGRANGE_CURVE = 68
  INTEGER, PARAMETER :: VTK_LAGRANGE_TRIANGLE = 69
  INTEGER, PARAMETER :: VTK_LAGRANGE_QUADRILATERAL = 70
  INTEGER, PARAMETER :: VTK_LAGRANGE_TETRAHEDRON = 71
  INTEGER, PARAMETER :: VTK_LAGRANGE_HEXAHEDRON = 72
  INTEGER, PARAMETER :: VTK_LAGRANGE_WEDGE = 73
  INTEGER, PARAMETER :: VTK_LAGRANGE_PYRAMID = 74

  INTEGER, PARAMETER :: VTK_NUMBER_OF_CELL_TYPES = 75
  
  END MODULE