subroutine write_readme_gmsh2sinp()	
	use DS_Gmsh2Solver
	use ifport
	implicit none
	integer::i,j,item
	LOGICAL(4)::tof,pressed,MSG
	!integer,external::ipp
	character(512)::readme(1024)
	
	open(2,file="D:\README_GMSH2SINP.G2S",STATUS='REPLACE')
	
	I=0
	README(IPP(I))= "//THE PROGRAM USES AN MSH FILE GENERATED BY THE GMSH AS AN INPUT FILE."
	README(IPP(I))= "//THE OUTPUT IS AN SINP FILE WHICH IS PREPARED FOR THE FEASOLVER AS AN INPUT FILE."
	README(IPP(I))= "//TO OUTPUT THE SINP FILE, ADDITIONAL INFORMATION IS NEED, WHICH IS PROVIDED BY SOME SELFDEFINED KEYWORDS."
	README(IPP(I)) ="//THE KEYWORD STRUCTURE IS EXPLAINED HEREIN"
	README(IPP(I)) ="//NOTE THAT NOT ALL OF THEM ARE REQUIRED TO SET UP THE MODEL."
	README(IPP(I)) ="//AND THAT THE DEPTH DIRECTION IS THE Z AXIS, WHOSE POSITIVE DIRECTION IS UPWARD.(KEEP CONSISTENCY WITH FEASOLVER)"
	README(IPP(I)) ="//所有的边界条件及荷载均以点作用的形式输出.ET=ELT_BC_OR_LOAD的单元组不输出."

	
	README(IPP(I)) ="\N//******************************************************************************************************"C
	README(IPP(I)) = "//$ELT_BC"
	README(IPP(I))=  "//"//'"'//"THE KEYWORD ELT_BC IS USED TO DEFINE THE BOUNDARY CONDITION APPLIED ON THE ELEMENT GROUP."//'"'
	README(IPP(I))="//NOTE THAT THE FINAL BC VALUE OF A NODE IS WHAT INPUT BY THE FIRST ELEMENT SHARING THE NODE."
	README(IPP(I))= "//{NELT_BC} "
	README(IPP(I)) = "//{NO,GROUPID,NDIM,DOF,STEPFUNC,VALUE,[A,B,C,D]}  // NDIM=0,1,2,3 分别表示点、线、面、体的约束. 因为边界条件（如位移，水头等）不具叠加性，所以NDIM取值对边界条件无影响."
    README(IPP(I)) = "//DOF=4(水头)，且VALUE=-999,表示节点的水头边界值为节点高程值。(模拟暴雨工况。)"
	README(IPP(I))=  "//                                                      // DOF(I)=1,2,...,7,分别表示约束X,Y,Z,H,MX,MY,MZ "
    README(IPP(I))=  "//[A,B,C,D] IS FOR LINEAR FIELD FUNCTION CALCULATION. IF THEY ARE PRESENT THEN VALUE=A*X+B*Y+C*Z+D. "
    README(IPP(I))=  "//NOTE: FOR THE LAYERED MODEL, THE GROUP IDS OF EACH EXTRUDED LAYERED IS REFERED AS GROUP_BASEMESH*100+ILAYER.AS SHOWN BELOW." 
	README(IPP(I))=  "//   -----------------								"
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   |    N-LAYER    | GROUPID=GROUP_BASEMESH*100+N   "
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   -----------------                                "
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   |    ..LAYER    |                                "
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   -----------------                                "
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   |    2-LAYER    | GROUPID=GROUP_BASEMESH*100+2   "
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   -----------------                                "
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   |    1-LAYER    | GROUPID=GROUP_BASEMESH         "
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   -----------------                                "
	README(IPP(I))=  "//{......}   //共NELT_BC行. "
	README(IPP(I)) = "//$ENDELT_BC"
	
	
	README(IPP(I)) ="\N//******************************************************************************************************"C
	README(IPP(I)) = "//$ELT_LOAD"
	README(IPP(I))=  "//"//'"'//"THE KEYWORD ELT_LOAD IS USED TO DEFINE THE LOAD APPLIED ON THE ELEMENT GROUP."//'"'
	README(IPP(I))="//NOTE THAT, IF THE NDIM=1,2 OR 3, THE FINAL BC VALUE OF A NODE IS THE SUM OF ALL THE ELEMENT SHARING THE NODE."
	README(IPP(I)) = "//{NELT_LOAD} "
	README(IPP(I)) = "//{NO,GROUPID,NDIM,DOF,STEPFUNC,VALUE,[A,B,C,D]}  // NDIM=0,1,2,3 分别表示点、线、面、体的荷载."
	README(IPP(I)) =  "//{......}   //共NELT_LOAD行. "
	README(IPP(I)) ="//目前可处理:NDIM=0(点荷载); "
	README(IPP(I)) ="//			 NDIM=1的情况目前可处理作用在2节点、3节点以及5节点的单元边，且仅限于均布线荷载;"
	README(IPP(I)) ="//			 NDIM=2的情况目前可处理作用在3节点（三角形）、4节点（四边形）、6节点（二次三角形）、8节点（二次四边形）以及15节点（四次三角形）的单元面，且仅限于均布面荷载;"
	README(IPP(I)) ="//			 NDIM=3的情况目前可处理作用在4节点（四面体）、10节点（二次四面体）、6节点(Prism)、8节点(长方体)，且仅限于均布体荷载;"
    README(IPP(I))=  "//[A,B,C,D] IS FOR LINEAR FIELD FUNCTION CALCULATION. IF THEY ARE PRESENT THEN VALUE=A*X+B*Y+C*Z+D. "
    README(IPP(I))=  "//NOTE: FOR THE LAYERED MODEL, THE GROUP IDS OF EACH EXTRUDED LAYERED IS REFERED AS GROUP_BASEMESH*100+ILAYER.AS SHOWN BELOW." 
	README(IPP(I))=  "//   -----------------								"
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   |    N-LAYER    | GROUPID=GROUP_BASEMESH*100+N   "
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   -----------------                                "
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   |    ..LAYER    |                                "
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   -----------------                                "
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   |    2-LAYER    | GROUPID=GROUP_BASEMESH*100+2   "
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   -----------------                                "
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   |    1-LAYER    | GROUPID=GROUP_BASEMESH         "
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   -----------------                                "
	README(IPP(I)) = "//$ENDELT_LOAD"		
	
	README(IPP(I)) ="\N//******************************************************************************************************"C
	README(IPP(I)) = "//$ELT_SPGFACE"
	README(IPP(I))=  "//"//'"'//"THE KEYWORD ELT_SPGFACE IS USED TO DEFINE THE SEEPAGEFACE CONDITION APPLIED ON THE ELEMENT GROUP."//'"'
	README(IPP(I)) = "//{NELT_SPGFACE} "
	README(IPP(I)) = "//{NO,GROUPID,NDIM,DOF,STEPFUNC,VALUE}  // NDIM=0,1,2,3 均可，VALUE=任意值（程序内部设为Y或Z）"
    README(IPP(I))=  "//NOTE: FOR THE LAYERED MODEL, THE GROUP IDS OF EACH EXTRUDED LAYERED IS REFERED AS GROUP_BASEMESH*100+ILAYER.AS SHOWN BELOW." 
	README(IPP(I))=  "//   -----------------								"
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   |    N-LAYER    | GROUPID=GROUP_BASEMESH*100+N   "
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   -----------------                                "
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   |    ..LAYER    |                                "
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   -----------------                                "
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   |    2-LAYER    | GROUPID=GROUP_BASEMESH*100+2   "
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   -----------------                                "
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   |    1-LAYER    | GROUPID=GROUP_BASEMESH         "
	README(IPP(I))=  "//   |               |                                "
	README(IPP(I))=  "//   -----------------                                "
	README(IPP(I)) =  "//{......}   //共NELT_SPGFACE行. "
	README(IPP(I)) = "//$ENDELT_SPGFACE"	
	
	!README(IPP(I)) ="\N//******************************************************************************************************"C
	!README(IPP(I)) = "//$MODELGROUP"
	!README(IPP(I))=  "//"//'"'//"THE KEYWORD MODELGROUP IS USED TO DEFINE THE GROUPS DEFINING THE MODEL, EXCLUDING THE GROUPS DEFINING THE BOUNDARIES."//'"'
	!README(IPP(I)) = "//{NMODELGROUP(I)} "
	!README(IPP(I)) = "//{GROUPID1(I),GROUPID2(I),...,GROUPIDN(I)}  // N=NMODELGROUP "
	!README(IPP(I)) = "//$ENDMODELGROUP"	
	
	README(IPP(I)) ="\N//******************************************************************************************************"C
	README(IPP(I)) = "//$WELLBORE"
	README(IPP(I))=  "//"//'"'//"THE KEYWORD WELLBORE IS USED TO DEFINE THE WELLBORE PARAMETERS."//'"'
	README(IPP(I)) = "//{NWELLBORE}   // 井集数"
    README(IPP(I)) = "//{Wellbore_GROUPID,WELL_HEAD_BC_TYPE,WellNODE_GroupID,VALUE [,SFN_GROUDID,NSEMI_SFN_GROUPS,PIPEFLOW_GroupID,NWELLSEEPAGEFACE]}" 
    README(IPP(I)) = "//{[SEMI_SFN_GROUDID,DIRECTION_VECTOR]} //ONLY NEED WHEN NSEMI_SFN_GROUPS>0 " 
    README(IPP(I)) = "//{[WELL_SEEPAGE_FACE_LINE_GROUPID,SINKNODE_GROUPID]} //ONLY NEED WHEN NWELLSEEPAGEFACE>0 " 
    README(IPP(I)) = "//WELL_HEAD_BC_TYPE,WellNODE_GroupID and Value:井点的边界类型、施加边界的节点GROUDID及数值。WELL_HEAD_BC_TYPE=0,1,2分别表示：自流井水头(水只出不进,但迭代过程中出现井流量为流入时，强制流量为0)，流量边界，常规定水头边界(不进行流量的正负检查);"
    README(IPP(I)) = "//SFN_GROUDID,附近为球状流的点集，模拟点源。=0(默认，无)=GROUPID(>0),球状流的位置由PHYSICALGROUP中单元决定" 
    README(IPP(I)) = "//NSEMI_SFN_GROUPS,半球状流的点集的个数，模拟非完整井。=0，无(默认，井为完整井)，=GROUPID(>0),半球状流的节点和方向由SEMI_SFN_GROUP和DIRECTION_VECTOR(半球区域方向矢量)中单元决定" 
    README(IPP(I)) = "//PIPEFLOW_GroupID,=0(默认全长均为滤管)，>0,管流管的位置由PHYSICALGROUP中单元决定 " 
    README(IPP(I)) = "//WELL_SEEPAGE_FACE_LINE_GROUPID和SINKNODE_GROUPID为潜水井井壁出溢线集和对应的井点(即各出溢点的流量汇入点)，每个潜水井对应一个出溢线集合和一个井点，所以SINKNODE_GROUPID只包含一个节点"
    !README(IPP(I)) = "目前，当井为潜水井时，出溢管是滤管的一部分，此时没有管流管。"
	README(IPP(I)) = "//$ENDWELLBORE"	    
    
	README(IPP(I)) ="\N//******************************************************************************************************"C
	README(IPP(I)) = "//$MODELDIMENSION"
	README(IPP(I))=  "//"//'"'//"THE KEYWORD MODELDIMENSION IS USED TO DEFINE THE MODEL DIMENSION."//'"'
	README(IPP(I)) = "//{MODELDIMENSION}   // MODELDIMENSION=2, 3"  
	README(IPP(I)) = "//$ENDMODELDIMENSION"	
	
	README(IPP(I)) ="\N//******************************************************************************************************"C
	README(IPP(I)) = "//$GROUPPARAMETER"
	README(IPP(I))=  "//"//'"'//"THE KEYWORD GROUPPARAMETER IS USED TO DEFINE THE MATERIAL AND ELEMENT TYPE IN THE MODELGROUP ELEMENTS."//'"'
	README(IPP(I)) = "//{NGROUPPARAMETER}"  
	README(IPP(I)) = "//{GROUDID,MATID(NLAYER),{COUPLESET},ET)}  //ET=CPE3,CPE6,TET4,TET10,....COUPLESET:耦合单元对，必要时（流固耦合）输入。"
	README(IPP(I)) = "//{......}  // 共NGROUPPARAMETER 个"     
	README(IPP(I)) = "//$ENDGROUPPARAMETER"	
    
	README(IPP(I)) ="\N//******************************************************************************************************"C
	README(IPP(I)) = "//$WSP"
	README(IPP(I))=  "//"//'"'//"THE KEYWORD WSP IS USED TO DEFINE THE BOUNDRAY LINE WHERE A WATER SURFACE PROFILE IS CALCULATED."//'"'
	README(IPP(I)) = "//{NWSP}"  
	README(IPP(I)) = "//{GROUPID,CHARACTERPOINTGROUP,STARTPOINTGROUP}*{NWSP}  // 每行3个，共NWSP行，STARTPOINTGROUP为输出起点(这个GROUP只含一个点)，根据起点按顺序输出线上各点。"
	README(IPP(I)) = "//注：CHARACTERPOINTGROUP，为从上游到下游流道的特征点。这些特征点将流道分成不同性质的子流道段"
	README(IPP(I)) = "//$ENDWSP"	
	
	README(IPP(I)) ="\N//******************************************************************************************************"C
	README(IPP(I)) = "//$DATAPOINT"
	README(IPP(I))=  "//"//'"'//"THE DataPoint IS USED TO OUTPUT THE DATA POINTS ALONG A POLYLINE YOU WANT TO LIST THE COMPUTATED RESULT."//'"'
	README(IPP(I)) = "//{NDataPoint)}"  
	README(IPP(I)) = "//{GROUPID [,ORDER=0,STARTPOINTGROUP,ISSUMQ]}*{NDataPoint(I)}  // 每行3个，共NDataPoint行.STARTPOINTGROUP为输出起点(这个GROUP只含一个点)，根据起点按顺序输出线上各点。ISSUM/=0,仅输出各点的流量和"
	README(IPP(I)) = "//ORDER=0,表示输出散点的形式（不排序）.=1，表示以STARTPOINTGROUP为起点按点的顺序输出。"
	README(IPP(I)) = "//$ENDDATAPOINT"		
	
	README(IPP(I)) ="\N//******************************************************************************************************"C
	README(IPP(I)) = "//$INCLUDEFILE"
	README(IPP(I))=  "//"//'"'//"THE INCLUDEFILE IS USED TO READ IN DATA IN ANOTHER FILE."//'"'
	README(IPP(I)) = "//{NINCLUDEFILE}"  
	README(IPP(I)) = "//{ABSOLUTED PATH OF THE FILES}*{NINCLUDEFILE(I)}  // 共NINCLUDEFILE行."
	README(IPP(I)) = "//$ENDINCLUDEFILE"    
	
	README(IPP(I)) ="\N//******************************************************************************************************"C
	README(IPP(I)) = "//$COPYFILE"
	README(IPP(I))=  "//"//'"'//"THE COPYFILE IS USED TO COPY DATA IN THE FILES TO THE OUTPUT FILE."//'"'
	README(IPP(I)) = "//{NCOPYFILE}"  
	README(IPP(I)) = "//{ABSOLUTED PATH OF THE FILES}*{NCOPYFILE(I)}  // 共NCOPYFILE行."
	README(IPP(I)) = "//$ENDCOPYFILE" 

    

	README(IPP(I)) ="\N//******************************************************************************************************"C
	README(IPP(I)) = "//$ELEVATION"
	README(IPP(I))=  "//"//'"'//"THE ELEVATION IS USED TO INPUT ELEVATION DATA FOR GENERATE PRISM/BRICK ELEMENT."//'"'
	README(IPP(I)) = "//NOTE THAT,THE BASE 2D ELEMENT MUST BE LINEAR."  
    README(IPP(I)) = "//A:{NNODE,NLAYER,[NSUBLAYER(NLAYER)]}    //节点数，地层数，每层细分层数"  
	README(IPP(I)) = "//B:{INODE,X,Y,Z(NLAYER+1)}*{NNODE}  // 共3+NLAYER+1个/行.Z IS IN A2Z ORDER(Z1<=Z2<=...<=Z(NLYAER+1)),共NNODE行"
	README(IPP(I)) = "//$ENDELEVATION"    

	README(IPP(I)) ="\N//******************************************************************************************************"C
	README(IPP(I)) = "//$TRISURFACE"
	README(IPP(I))=  "//"//'"'//"THE TRISURFACE IS USED TO INPUT CONTROL DATA FOR GENERATE TRISURFACE DATA."//'"'
    README(IPP(I)) = "//A:{ISGEO,ISSTL,ISOFF}    //(1,YES;0,NO)"  
	README(IPP(I)) = "//$ENDTRISURFACE"  
    
	README(IPP(I)) ="\N//******************************************************************************************************"C
	README(IPP(I)) = "//$OFF_MERGE"
	README(IPP(I))=  "//"//'"'//"THE OFF_MERGE IS USED TO MERGE OFF MESHES INTO A CONSISTENT MESH WITHOUT DUPLICATED NODES."//'"'
    README(IPP(I)) = "//NOTE THAT THE NODE NUMBER OF EACH FACE MUST BE 3 AND 4." 
	README(IPP(I)) = "//A:{NOFF,[TOL]}    //NUMBER OF THE FILES,TOLERANCE,THE DEFAULT VALUE=0.0001" 
	README(IPP(I)) = "//B:{GROUPID,DIM,FILENAME_WITH_PATH}*{NOFFFILE}    //ID(MUST BE <=100);DIM=2,SURFACE;DIM=3,VOLUME;FILE NAMES, THERE SHOULD BE NOFFILE ROWS " 
	README(IPP(I)) = "//$ENDOFF_MERGE"    

    README(IPP(I)) ="\N//******************************************************************************************************"C
	README(IPP(I)) = "//$NOPOPUP"
	README(IPP(I))=  "//"//'"'//"THE NOPOPUP IS USED TO STOP INTERACTION INFO DIALOG."//'"'
    README(IPP(I)) = "//A:{1|0}    //1:YES,0:NO(DEFAULT)"  
	README(IPP(I)) = "//$ENDNOPOPUP" 
	
    README(IPP(I)) ="\N//******************************************************************************************************"C
	README(IPP(I)) = "//$OUTMESHSTRUCTURE"
	README(IPP(I))=  "//"//'"'//"WHETHER TO OUT MESHSTRUCTURE."//'"'
    README(IPP(I)) = "//A:{1|0}    //1:YES,0:NO(DEFAULT)"  
	README(IPP(I)) = "//$OUTMESHSTRUCTURE" 	
    
	do 	j=1,i
		item=len_trim(readme(j))
		write(2,20) readme(j)
	end do
    
    close(2)
	
!	tof=system("D:\README_GMSH2SINP.TXT")	
	
20	format(a<item>)
	
	contains
	
	integer function ipp(i) 
		implicit none
		integer,intent(inout)::i
		
		i=i+1
		ipp=i
		if(ipp>1024) then
			print *, "The size of README is 1024."
			stop
		end if
				
	end function
	
end subroutine
